"""initial schema

Revision ID: 1191f897e69e
Revises: 
Create Date: 2026-06-29 23:31:33.814907
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1191f897e69e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('registration_no', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_no')
    )
    op.create_table('users',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('HOSPITAL_ADMIN', 'DOCTOR', 'RADIOLOGIST', 'STAFF', 'SYSTEM', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('license_no', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('sign_pin_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_role', sa.Enum('HOSPITAL_ADMIN', 'DOCTOR', 'RADIOLOGIST', 'STAFF', 'SYSTEM', name='userrole'), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'PATIENT_REGISTERED', 'SCAN_UPLOADED', 'AI_COMPLETE', 'REPORT_SIGNED', 'REPORT_CERTIFIED', 'PDF_EXPORTED', 'FLAG_RAISED', 'RE_ANALYSIS_REQUESTED', name='auditaction'), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILURE', name='auditresult'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('mrn', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('cnic', sa.String(length=40), nullable=True),
    sa.Column('contact', sa.String(length=40), nullable=True),
    sa.Column('referring_doctor_id', sa.UUID(), nullable=True),
    sa.Column('ward', sa.String(length=120), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', 'EMERGENCY', name='priority'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['referring_doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    op.create_table('scans',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('scan_type', sa.Enum('PA', 'AP', 'LATERAL', name='scantype'), nullable=False),
    sa.Column('scan_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('equipment', sa.String(length=255), nullable=True),
    sa.Column('radiologist_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'ANALYZED', 'FAILED', 'FLAGGED', name='scanstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_analyses',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('analysis_ref', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('label', sa.Enum('PNEUMONIA_DETECTED', 'SUSPECTED', 'NORMAL', name='ailabel'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('MILD', 'MODERATE', 'SEVERE', name='severity'), nullable=True),
    sa.Column('lung_zone', sa.String(length=80), nullable=True),
    sa.Column('laterality', sa.String(length=40), nullable=True),
    sa.Column('pattern', sa.String(length=80), nullable=True),
    sa.Column('confidence_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('heatmap_path', sa.String(length=512), nullable=True),
    sa.Column('icd_suggestion', sa.String(length=20), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_ref'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_table('reports',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('report_no', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AI_READY', 'IN_REVIEW', 'FLAGGED', 'DOCTOR_SIGNED', 'CERTIFIED', 'DELIVERED', name='reportstatus'), nullable=False),
    sa.Column('clinical_findings', sa.Text(), nullable=True),
    sa.Column('diagnosis_agreement', sa.Enum('CONFIRM', 'PARTIAL', 'DISAGREE', name='diagnosisagreement'), nullable=True),
    sa.Column('icd_code', sa.String(length=20), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('followup_instructions', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_index(op.f('ix_reports_report_no'), 'reports', ['report_no'], unique=True)
    op.create_table('signatures',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('signer_id', sa.UUID(), nullable=False),
    sa.Column('signature_type', sa.Enum('DOCTOR', 'HOSPITAL', name='signaturetype'), nullable=False),
    sa.Column('signature_hash', sa.String(length=128), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signatures')
    op.drop_index(op.f('ix_reports_report_no'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('ai_analyses')
    op.drop_table('scans')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
